name: my_wallet
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  auto_size_text: 3.0.0
  change_app_package_name: ^1.5.0
  circular_reveal_animation: ^2.0.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_native_timezone: 2.0.0
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  hive_flutter: 1.1.0
  intl: ^0.20.2
  month_year_picker: ^0.5.0+1
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^31.2.15
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: commonFont
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
